# Generated by Django 5.1.2 on 2025-01-15 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photofrom',
        ),
        migrations.AlterField(
            model_name='photo',
            name='memorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='app.memorial'),
        ),
    ]
