# Generated by Django 5.1.2 on 2025-01-15 14:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_photo_photofrom_alter_photo_memorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='datepost',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
