# Generated by Django 5.1.2 on 2025-01-29 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_message_dateposted_alter_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='memorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.memorial'),
        ),
    ]
