# Generated by Django 5.1.2 on 2025-01-29 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_message_memorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='dateposted',
            field=models.DateTimeField(null=True, verbose_name=datetime.date(2025, 1, 29)),
        ),
    ]
