# Generated by Django 5.1.2 on 2025-01-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_message_dateposted_reaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='message',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
